# Generated by Django 6.1 on 2026-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20, unique=True)),
                ('functional_unit', models.CharField(choices=[('BIL', 'БИЛ'), ('BIK', 'БИК'), ('CONTROL_ROOM', 'Аппаратная'), ('BSE', 'БСЭ')], max_length=20)),
                ('status', models.CharField(choices=[('WORK', 'В работе'), ('SPARE', 'ЗИП'), ('REPAIR', 'В ремонте'), ('VERIFICATION', 'На поверке')], default='WORK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'type_model', 'serial_number'],
                'constraints': [models.UniqueConstraint(fields=('type_model', 'serial_number'), name='unique_instrument_type_model_serial_number')],
            },
        ),
    ]
