# Generated by Django 6.1 on 2026-09-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
