# Generated by Django 6.1 on 2026-10-10 04:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Проверяемый сайт')),
                ('control_url', models.URLField(default='https://ya.ru/', help_text='Укажите сайт, доступный у вашего оператора при белых списках.', max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Контрольный сайт')),
                ('interval_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Интервал, минут')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Таймаут, секунд')),
                ('is_active', models.BooleanField(default=True, verbose_name='Проверки включены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('state', models.CharField(choices=[('unknown', 'Ещё не проверен'), ('online', 'Онлайн'), ('restricted', 'Возможны белые списки'), ('site_down', 'Сайт недоступен'), ('network_down', 'Проблема подключения')], default='unknown', max_length=20, verbose_name='Состояние')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('next_check_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующая проверка')),
            ],
            options={
                'verbose_name': 'Монитор',
                'verbose_name_plural': 'Мониторы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MonitorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('previous_state', models.CharField(choices=[('unknown', 'Ещё не проверен'), ('online', 'Онлайн'), ('restricted', 'Возможны белые списки'), ('site_down', 'Сайт недоступен'), ('network_down', 'Проблема подключения')], max_length=20)),
                ('state', models.CharField(choices=[('unknown', 'Ещё не проверен'), ('online', 'Онлайн'), ('restricted', 'Возможны белые списки'), ('site_down', 'Сайт недоступен'), ('network_down', 'Проблема подключения')], max_length=20)),
                ('message', models.CharField(max_length=500, verbose_name='Уведомление')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitoring.monitor')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления Web Monitor',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время проверки')),
                ('url', models.URLField(max_length=2048)),
                ('control_url', models.URLField(max_length=2048)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время ответа, мс')),
                ('is_up', models.BooleanField(verbose_name='Сайт доступен')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка сайта')),
                ('control_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('control_error_message', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('unknown', 'Ещё не проверен'), ('online', 'Онлайн'), ('restricted', 'Возможны белые списки'), ('site_down', 'Сайт недоступен'), ('network_down', 'Проблема подключения')], max_length=20, verbose_name='Состояние')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.monitor')),
            ],
            options={
                'verbose_name': 'Проверка',
                'verbose_name_plural': 'История проверок',
                'ordering': ['-checked_at', '-pk'],
                'indexes': [models.Index(fields=['monitor', '-checked_at'], name='monitoring__monitor_f8e817_idx')],
            },
        ),
    ]
